Prohibit contrast degradation for styles via test
Web accessibility is important. Unfortunately currently many pygments
styles have rules with poor contrasts. This commit introduces a test
case that fails if the minimum contrast of a style gets worse, e.g:

E  AssertionError: contrast degradation for style 'borland'
E    The following rules have a contrast lower than the required 2.9:
E
E    * 1.90 Token.Text.Whitespace
E    * 2.80 Token.Generic.Heading
E    * 2.30 Token.Generic.Subheading
E
E  assert not 1.9 < 2.9

This is accomplished by storing the current minimum contrasts in
./tests/contrast/min_contrasts.json.

When you improve a minimum contrast the test fails with:

E  AssertionError: congrats, you improved a contrast! please run ./scripts/update_contrasts.py
E  assert not 1.9 > 0.9

Running the script as instructed updates the JSON file, making the test pass.

New styles are required to meet the WCAG AA contrast minimum of 4.5.

First commit to address #1718.